using UnityEngine;
using System.Collections;

public class Movement : MonoBehaviour {

	public Rigidbody rb;
	public float speed;
	
	
	// Use this for initialization
	void Start () {
		rb = GetComponent<Rigidbody>();
		
	}
	
	// Update is called once per frame
	void Update () {
		
	}
	
	void FixedUpdate () {
		rb.velocity = transform.forward * speed + Physics.gravity;
		
		
		Ray moveRay = new Ray( transform.position, transform.forward) ;
		Debug.DrawRay ( moveRay.origin, moveRay.direction );
		
		if ( Physics.Raycast ( moveRay, 1f ) ) {
			int randomNumber = Random.Range (0, 2); // random num, 0 or 1
			if ( randomNumber == 0) {
				// turn left
				transform.Rotate (0f, -90f, 0f);
			} else {
				// turn right
				transform.Rotate (0f, 90f, 0f);
			}
		}
}
}
